#!/bin/sh
exec chat	-v \
ECHO             ON \
TIMEOUT      26 \
ABORT          'BUSY' \
ABORT          'ERROR' \
ABORT          'NO CARRIER'	\
ABORT          'NO DIALTONE' \
ABORT          'RINGING\r\n\r\nRINGING' \
TIMEOUT      1 \
SAY "\nPress CTRL-C to close the connection at any stage!\n" \
'' AT	 \
TIMEOUT      3 \
OK                AT+CSQ \
OK		AT+CFUN=0 \
TIMEOUT      26 \
OK 		AT+CFUN=1 \
TIMEOUT      26 \
'PB DONE' AT \
OK	AT+QENG=\"servingcell\" \
OK                ATH \
OK                ATE1 \
OK   'AT+CGDCONT=1,"IP","wlwmimo.vpdn.cq"' \
OK                'ATD*99***1#' \
TIMEOUT     60 \
SAY "\nWaiting for Connect......\n" \
CONNECT  "" \
SAY "\nConnect Success!\n"\